sudo: required
services:
  - docker

before_install:
  - docker build -t ksreddy4599/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true ksreddy4599/react-test npm run test ----watchAll=false --coverage

after_success:
  - docker build -t ksreddy4599/fibonacci-client ./client 
  - docker build -t ksreddy4599/fibonacci-nginx ./nginx
  - docker build -t ksreddy4599/fibonacci-server ./server
  - docker build -t ksreddy4599/fibonacci-worker ./worker

  #Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Take these images and push them to the docker hub
  - docker push ksreddy4599/fibonacci-client
  - docker push ksreddy4599/fibonacci-nginx
  - docker push ksreddy4599/fibonacci-server
  - docker push ksreddy4599/fibonacci-worker

